homepage: null
bugtracker: http://www.github.com/jfdm/idris-config/issues
packages:
- containers
- effects
- lightyear
- test
- testparse
name: config
version: '0.1'
brief: Simple config file parser
sourceloc:
  git: git@github.com:jfdm/idris-config.git
license: BSD3 but see LICENSE for more information
